# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 538f019c0ff5da204a79a992e7823eeb63452cec4e804bbb9c11c95cdf17f422899ed1be8d2240800ee79676ad4cad94f1d63e72751275b985c6b0ab12d1fa8d

test:
  secret_key_base: b6a75e9761babd591e9b0136e3688583e27a2454a9c2b8678c271bec0761095df2ed8c7ae3a564d3138d7df6184d9673e7543e2365759e78e3b9c18ffa6c4428

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
